// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using test.Models;

#nullable disable

namespace test.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20231209093614_DbCategoryToModuls")]
    partial class DbCategoryToModuls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("test.Models.Categors.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("test.Models.Categors.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModuleName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("test.Models.Categors.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorysId")
                        .HasColumnType("integer");

                    b.Property<string>("SubcategoryName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("СategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategorysId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("test.Models.Categors.Module", b =>
                {
                    b.HasOne("test.Models.Categors.Subcategory", "Subcategories")
                        .WithMany("Moduls")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("test.Models.Categors.Subcategory", b =>
                {
                    b.HasOne("test.Models.Categors.Category", "Categorys")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategorysId");

                    b.Navigation("Categorys");
                });

            modelBuilder.Entity("test.Models.Categors.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("test.Models.Categors.Subcategory", b =>
                {
                    b.Navigation("Moduls");
                });
#pragma warning restore 612, 618
        }
    }
}
